# coding: utf-8
"""一键生成 Big QMT 桥接两端的真实配置（输入资金账号 → 自动算 ZMQ 端口）。

用法（在 bridge_client/ 目录下运行）：
    python gen_config.py

交互输入：
    1) 资金账号（必填，如 1234567890）
    2) 账号类型（默认 STOCK；信用账户填 CREDIT）
    3) 是否允许远程下单/撤单（默认 Y；一旦开启就是真实委托，测试务必用小单）

生成文件（均含账号，已被 .gitignore 排除，不会进 GitHub）：
    server/bigqmt_signal_trader_local_config.py   ← 复制到 QMT 的 python/ 用
    client/bigqmt_signal_trader_client_config.py   ← 本机 xxybacktest 用

ZMQ 端口规则：15560 + (账号末两位)。例如账号 1234567890 → 端口 15650。
两端端口自动一致，无需手填。

渲染格式与上游 `bigqmt_signal_trader.init_config` 的 render_* 完全一致，
桥接加载层按此读取，请勿随意增减字段。
"""
import os

DEFAULT_ZMQ_BASE = 15560
VALID_ACCOUNT_TYPES = (
    "STOCK", "CREDIT", "FUTURE", "STOCK_OPTION", "HUGANGTONG", "SHENGANGTONG",
)


def zmq_port(account_id):
    """端口推导唯一真源：15560 + (账号 % 100)。与上游 ZmqTransport 一致。"""
    return DEFAULT_ZMQ_BASE + (int(account_id) % 100)


def _zmq_bind_host(client_host):
    normalized = str(client_host or "").strip().lower()
    if normalized in ("", "127.0.0.1", "localhost"):
        return "127.0.0.1"
    return "0.0.0.0"


def render_server_config(account_id, account_type="STOCK", host="127.0.0.1",
                          allow_order=True):
    port = zmq_port(account_id)
    bind_host = _zmq_bind_host(host)
    lines = [
        "# coding: utf-8",
        '"""Local private config for the QMT python directory.',
        "",
        "Generated by bridge_client/gen_config.py.",
        "DO NOT COMMIT: this file holds an account id.",
        '"""',
        "",
        "BIGQMT_ACCOUNT_ID = %r" % str(account_id),
        "",
        "BIGQMT_ACCOUNT_TYPE = %r" % str(account_type),
        "",
        "BIGQMT_REDIS_CONFIG = {",
        '    "transport": "zmq",',
        '    "host": %r,' % host,
        '    "port": 6379,',
        '    "db": 5,',
        '    "username": "",',
        '    "password": "",',
        '    "zmq": {"bind_address": "tcp://%s:%d"},' % (bind_host, port),
    ]
    if allow_order:
        lines.append('    # Remote order/cancel is ON. Turn it off if you only need queries.')
    else:
        lines.append('    # Remote order/cancel stays off until you explicitly want it.')
    lines.extend([
        '    "rpc_allow_order_methods": %r,' % bool(allow_order),
        '    "rpc_process_in_listener": True,',
        '    "rpc_listener_methods": ("*",),',
        '    "rpc_background_threads": False,',
        '    "schedule_adjust": True,',
        '    "schedule_adjust_interval": "100nMilliSecond",',
        '    "full_tick_cache_enabled": False,',
        '    "full_tick_demand_ttl_seconds": 10,',
        '    "full_tick_cache_ttl_seconds": 10,',
        '    "full_tick_refresh_interval_seconds": 0.5,',
        '    "full_tick_market_refresh_interval_seconds": 3,',
        '    "full_tick_refresh_max_wall_seconds": 0.3,',
        '    "full_tick_max_requests": 8,',
        '    "download_jobs_enabled": False,',
        '    "download_job_chunk_size": 10,',
        '    "download_job_max_wall_seconds": 0.5,',
        '    "download_job_ttl_seconds": 3600,',
        '    "exec_events_enabled": True,',
        '    "exec_events_debug_raw_fields": False,',
        "}",
        "",
    ])
    return "\n".join(lines)


def render_client_config(account_id, host="127.0.0.1", allow_order=True):
    port = zmq_port(account_id)
    lines = [
        "# coding: utf-8",
        '"""Client-side private config.',
        "",
        "Generated by bridge_client/gen_config.py.",
        "DO NOT COMMIT: this file holds an account id.",
        '"""',
        "",
        "BIGQMT_ACCOUNT_ID = %r" % str(account_id),
        "BIGQMT_RPC_TIMEOUT_SECONDS = 30.0",
        "",
        "BIGQMT_REDIS_CONFIG = {",
        '    "transport": "zmq",',
        '    "host": %r,' % host,
        '    "port": 6379,',
        '    "db": 5,',
        '    "username": "",',
        '    "password": "",',
        '    "zmq": {',
        '        "host": %r,' % host,
        '        "port": %d,' % port,
        '        "connect_address": "tcp://%s:%d",' % (host, port),
        "    },",
        "}",
        "",
        "BIGQMT_FORMULA_SERVER_CONFIG = {",
        '    "enabled": True,',
        "}",
        "",
        "BIGQMT_LOCAL_CACHE_CONFIG = {",
        '    "enabled": True,',
        '    "dir": None,',
        '    "fallback_rpc": False,',
        '    "format": "auto",',
        "}",
        "",
    ]
    return "\n".join(lines)


def _ask(prompt, default=""):
    try:
        raw = input("%s%s: " % (prompt, " [%s]" % default if default != "" else "")).strip()
    except EOFError:
        raw = ""
    return raw if raw else default


def _ask_bool(prompt, default=True):
    hint = "Y/n" if default else "y/N"
    try:
        raw = input("%s [%s]: " % (prompt, hint)).strip().lower()
    except EOFError:
        raw = ""
    if not raw:
        return default
    return raw in ("y", "yes", "是", "1", "true")


def main():
    here = os.path.dirname(os.path.abspath(__file__))
    server_dir = os.path.join(here, "server")
    client_dir = os.path.join(here, "client")

    print("\n=== Big QMT 桥接配置生成 ===")
    account_id = ""
    while not account_id:
        account_id = _ask("资金账号（必填，如 1234567890）")
        if not account_id:
            print("  账号不能为空。")
    if not account_id.isdigit():
        print("  警告：账号非纯数字，端口推导可能异常，请确认输入正确。")

    account_type = _ask("账号类型", "STOCK")
    if account_type.upper() not in VALID_ACCOUNT_TYPES:
        print("  未知类型 %r，回退为 STOCK。" % account_type)
        account_type = "STOCK"

    print("\n远程下单/撤单默认开启。开启后任何能连上这条通道的程序都可以下真实委托。")
    allow_order = _ask_bool("允许远程下单/撤单？", True)

    server_text = render_server_config(account_id, account_type, "127.0.0.1", allow_order)
    client_text = render_client_config(account_id, "127.0.0.1", allow_order)

    server_path = os.path.join(server_dir, "bigqmt_signal_trader_local_config.py")
    client_path = os.path.join(client_dir, "bigqmt_signal_trader_client_config.py")

    with open(server_path, "w", encoding="utf-8", newline="\n") as f:
        f.write(server_text)
    with open(client_path, "w", encoding="utf-8", newline="\n") as f:
        f.write(client_text)

    port = zmq_port(account_id)
    print("\n=== 已写入 ===")
    print("  " + server_path)
    print("  " + client_path)
    print("\n账号: %s | ZMQ 端口: %d | 传输: zmq | 下单: %s"
          % (account_id, port, "开启" if allow_order else "关闭"))
    print("\n这些文件含账号，已被 .gitignore 排除，不要提交到 GitHub。")
    print("下一步：把 server/ 整个目录复制到 QMT 的 python/，在 QMT 里运行 BIGQMT_ZMQ_DRYRUN.py。")


if __name__ == "__main__":
    main()
